import {
  Loader2,
  Sparkles,
  Trash2,
  ChevronLeft,
  ChevronRight,
  Calendar,
  Mail,
  Link,
  FileText,
  DollarSign,
  Building,
  Briefcase,
  CheckCircle,
  XCircle,
  Clock,
  LucideArrowRight,
  LucideBarChart2,
  LucideBrainCog,
  LucideClipboardList,
  LucideInfo,
  LucideRocket,
  Search,
  Plus,
  Pencil,
  Save,
  // Add more icons as needed
} from "lucide-react";

export const Icons = {
  save: Save,
  chevronLeft: ChevronLeft,
  fileText: FileText,
  edit: Pencil,
  search: Search,
  plus: Plus,
  rocket: LucideRocket,
  info: LucideInfo,
  ai: LucideBrainCog,
  track: LucideClipboardList,
  insights: LucideBarChart2,
  arrowRight: LucideArrowRight,
  spinner: Loader2,
  sparkles: Sparkles,
  trash: Trash2,

  chevronRight: ChevronRight,
  calendar: Calendar,
  mail: Mail,
  link: Link,
  file: FileText,
  dollar: DollarSign,
  building: Building,
  briefcase: Briefcase,
  check: CheckCircle,
  x: XCircle,
  clock: Clock,
  // Add more icons as needed
};

export type IconName = keyof typeof Icons;
